### ISSUE TITLE
It isn't possible to pass a string containing a JAVA environment variable

### ISSUE THREAD

**Issue by akkie** [connaryscott/bamboo-rundeck-plugin#1]
If I create an inline script in the following form:

```
-project.opts "-Dhttp.port=8081 -Dconfig.resource=application.staging.conf"
```

Then I get the following error message:

```
(com.atlassian.bamboo.task.TaskException : jobArgs format error, param: null does not begin with -)
```

It would be cool if the Plugin does allow such a construct. Or is there any workaround?

**Comment by connaryscott** [comment]
Hi Christian,

I will take a look at the options parser.  Perhaps the embedded ­D
parameters are confusing it and likely a bug.

From:  Christian Kaps notifications@github.com
Reply-To:  connaryscott/bamboo-rundeck-plugin
<reply+i-12285860-b9879432ed90bcc72d7b680a8888b362b18cf587-571449@reply.gith
ub.com>
Date:  Thursday, March 21, 2013 10:31 AM
To:  connaryscott/bamboo-rundeck-plugin
bamboo-rundeck-plugin@noreply.github.com
Subject:  [bamboo-rundeck-plugin] It isn't possible to pass a string
containing a JAVA environment variable (#1)

If I create an inline script in the following form:
-project.opts "-Dhttp.port=8081 -Dconfig.resource=application.staging.conf"
Then I get the following error message:
(com.atlassian.bamboo.task.TaskException : jobArgs format error, param: null
does not begin with -)
It would be cool if the Plugin does allow such a construct. Or is there any
workaround?

‹
Reply to this email directly or view it on GitHub
https://github.com/connaryscott/bamboo-rundeck-plugin/issues/1 .
